'use client';
import {useState} from 'react';
import {estimate,serviceNames,type Service} from '@/lib/pricing';
import {site} from '@/lib/site.config';
import {bookUrlForService} from './BookLink';
export default function Estimator({initialService='cleaning'}:{initialService?:Service}){
 const[service,setService]=useState<Service>(initialService),[stories,setStories]=useState(1),[size,setSize]=useState(0);
 const result=estimate(service,stories,size,site.LICENSED);const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
 return <><div className="estimator"><div className="estimate-controls"><span className="eyebrow">YOUR HOME, YOUR ESTIMATE</span><h3 style={{marginTop:12}}>Get your price.</h3><label className="field">01 — What can we help with?<select value={service} onChange={e=>setService(e.target.value as Service)}>{Object.entries(serviceNames).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><div className="field"><span id="stories-label">02 — How many stories?</span><div className="segmented" role="group" aria-labelledby="stories-label">{[1,2,3].map(n=><button type="button" key={n} aria-pressed={stories===n} onClick={()=>setStories(n)}>{n} {n===1?'story':'stories'}</button>)}</div></div><label className="field">03 — Approximate home size<select value={size} onChange={e=>setSize(Number(e.target.value))}>{['Under 1,500 sq ft','1,500–2,500 sq ft','2,500–3,500 sq ft','Over 3,500 sq ft'].map((s,i)=><option value={i} key={s}>{s}</option>)}</select></label></div><div className="estimate-result"><span className="eyebrow">A CLEAR STARTING POINT</span><div aria-live="polite" aria-atomic="true"><div className="price">{service==='roof'?'Not scheduling':result.custom?'Custom quote needed':`${money(result.low!)}–${money(result.high!)}`}</div><p>{service==='roof'?'Roof washes are not on the calendar until coverage includes roof height. Book a house wash, or leave a message for Dre.':result.custom?'We need a closer look before we can quote this scope. Book a visit and we will confirm the price on site.':'Estimated price, confirmed on site. Includes the service selected above. Access and condition may affect your quote.'}</p></div>{bookUrlForService(service)&&<a className="button" href={bookUrlForService(service)!} target="_blank" rel="noopener noreferrer">Book a visit <span>↗</span></a>}<p className="price-note">Starting prices. Final price confirmed on site before any work begins.</p><p className="call-line">Or call <a href={site.PHONE_HREF}>{site.PHONE_MAIN}</a></p></div></div></>;
}
