'use client';
import {useState,useEffect,useRef} from 'react';
import Script from 'next/script';
import {serviceNames,type Service} from '@/lib/pricing';
declare global {interface Window {turnstile?:{render:(el:HTMLElement,options:Record<string,unknown>)=>string;reset:(id:string)=>void;remove:(id:string)=>void}}}
export default function LeadForm({service='cleaning',stories=1,size=0,newHome=false,intent='service',chooseService=false}:{service?:Service;stories?:number;size?:number;newHome?:boolean;intent?:'service'|'membership'|'commercial'|'new-home';chooseService?:boolean}){
 const[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[token,setToken]=useState(''),[ready,setReady]=useState(false);const captcha=useRef<HTMLDivElement>(null),widget=useRef<string|undefined>(undefined);const key=process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY;
 useEffect(()=>{const params=new URLSearchParams(location.search);const utm=Object.fromEntries(['utm_source','utm_medium','utm_campaign','utm_content','utm_term'].map(k=>[k,params.get(k)?.slice(0,200)]).filter(([,v])=>v));if(Object.keys(utm).length)try{sessionStorage.setItem('chaffee_source',JSON.stringify(utm))}catch{}},[]);
 useEffect(()=>{if(ready&&key&&captcha.current&&window.turnstile){widget.current=window.turnstile.render(captcha.current,{sitekey:key,callback:(t:string)=>setToken(t),'expired-callback':()=>setToken('')});return()=>{if(widget.current)window.turnstile?.remove(widget.current)}}},[ready,key]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setMessage('');const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));let utm={};try{utm=JSON.parse(sessionStorage.getItem('chaffee_source')||'{}')}catch{}
 try{const r=await fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,service:chooseService?data.service:service,intent:newHome?'new-home':intent,stories,size,smsConsent:data.smsConsent==='on',turnstileToken:token,utm,source:location.pathname})});const result=await r.json();if(!r.ok)throw new Error(result.error||'Your request could not be sent. Please try again.');setDone(true);setMessage('Request received. We’ll contact you to confirm the scope and appointment. Your date is not booked yet.');form.reset()}catch(err){setMessage(err instanceof Error?err.message:'Unable to send. Please try again.');if(widget.current)window.turnstile?.reset(widget.current);setToken('')}finally{setBusy(false)}}
 return <form className="lead-form" onSubmit={submit}><div className="form-grid"><label className="field">Your name<input autoComplete="name" name="name" required maxLength={100} placeholder="First and last name"/></label><label className="field">Phone number<input type="tel" name="phone" autoComplete="tel" required maxLength={20} placeholder="(479) 555-0123" onChange={e=>{const n=e.target.value.replace(/\D/g,'').slice(0,10);e.target.value=n.length>6?`(${n.slice(0,3)}) ${n.slice(3,6)}-${n.slice(6)}`:n.length>3?`(${n.slice(0,3)}) ${n.slice(3)}`:n}}/></label><label className="field full">Service address<input autoComplete="street-address" name="address" required maxLength={250} placeholder="Street address, city, ZIP"/></label><label className="field">Preferred date<input type="date" name="date" min={new Date().toLocaleDateString('en-CA')} required/></label>{newHome?<label className="field">Does your home have gutters?<select name="gutters"><option>Yes</option><option>Some</option><option>No</option></select></label>:chooseService?<label className="field">Requested service<select name="service" defaultValue={service}>{Object.entries(serviceNames).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label>:<div className="field">Requested service<div style={{padding:'12px 0'}}>{serviceNames[service]}</div></div>}</div><div className="hp" aria-hidden="true"><label>Leave empty<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="consent"><input type="checkbox" name="smsConsent"/><span>I agree to receive service-related texts from Chaffee Exteriors at the number provided. Consent is not a condition of purchase. Message and data rates may apply. Frequency varies. Reply STOP to opt out or HELP for help. See our <a href="/sms" target="_blank" rel="noopener">SMS terms</a> and <a href="/privacy" target="_blank" rel="noopener">privacy policy</a>.</span></label>{key&&<><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit" onReady={()=>setReady(true)}/><div ref={captcha}/></>}<button className="button" disabled={busy||done||Boolean(key&&!token)} type="submit">{busy?'Sending…':done?'Request received':'Send my request'} <span>↗</span></button><p className="price-note">{process.env.NEXT_PUBLIC_LEADS_ENABLED==='true'?'A preferred date is a request, not a confirmed appointment.':'Website preview: live lead delivery is not connected yet.'}</p>{message&&<p className="form-message" role="status">{message}</p>}</form>
}
