import Link from 'next/link';
import {ServiceMenu,MobileMenu} from '@/components/NavMenus';
import {BookLink} from '@/components/BookLink';
import {site} from '@/lib/site.config';
import {MARK,MARK_VIEWBOX,WORDMARK_MAIN,WORDMARK_SUB,WORDMARK_VIEWBOX} from '@/lib/brand-paths';
export function Mark({className}:{className?:string}){return <svg className={'brand-mark '+(className||'')} viewBox={MARK_VIEWBOX} aria-hidden="true"><path className="m-roof" d={MARK.roof}/><path className="m-rail" d={MARK.rail}/><path className="m-drop" d={MARK.drop}/></svg>}
export function Wordmark(){return <svg className="brand-word" viewBox={WORDMARK_VIEWBOX} aria-hidden="true"><path className="w-main" d={WORDMARK_MAIN}/><path className="w-sub" d={WORDMARK_SUB}/></svg>}
export function Logo({linked=true,reverse=false}:{linked?:boolean;reverse?:boolean}){const inner=<><Mark/><Wordmark/><span className="sr-only">Chaffee Exteriors</span></>;const cls='brand'+(reverse?' brand-reverse':'');return linked?<Link href="/" className={cls} aria-label="Chaffee Exteriors home">{inner}</Link>:<div className={cls}>{inner}</div>}
export function Header(){return <><div className="utility"><span>FORT SMITH ROOTS. RIVER VALLEY REACH.</span><span>Gutters · Guards · Exterior care</span></div><header className="header container"><Logo/><nav aria-label="Main navigation"><ServiceMenu/><Link href="/membership">Home protection</Link><Link href="/learn">Guides</Link><Link href="/about">Our story</Link></nav>{site.PHONE_MAIN&&<a className="header-phone" href={site.PHONE_HREF}>{site.PHONE_MAIN}</a>}<BookLink>Book a visit <span>↗</span></BookLink><MobileMenu/></header></>}
export function Footer(){return <footer className="footer"><div className="container footer-top"><div><Logo reverse/><p>Precision from the roofline down.</p><a className="contact-link" href={site.PHONE_HREF}>{site.PHONE_MAIN}</a><a className="contact-link" href={"mailto:"+site.EMAIL}>{site.EMAIL}</a><p>Serving {site.SERVICE_AREAS.join(", ")}.</p><span className="eyebrow">FORT SMITH, ARKANSAS</span></div><div><h3>Keep your home ready.</h3><Link href="/gutter-cleaning">Gutter cleaning</Link><Link href="/gutter-guards">Gutter guards</Link><Link href="/gutter-repair">Gutter repair</Link><Link href="/soft-wash">Soft washing</Link><Link href="/holiday-lights">Holiday lights</Link><Link href="/porch-decorating">Porch decorating</Link></div><div><h3>Good to know.</h3><Link href="/about">Our story</Link><Link href="/membership">Membership</Link><Link href="/realtors">For property professionals</Link><Link href="/learn">Homeowner guides</Link><Link href="/contact">Get in touch</Link></div></div><div className="footer-watermark" aria-hidden="true"><Wordmark/></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} {site.LEGAL_NAME||site.name} · Fort Smith & the River Valley{site.CITY_LICENSE_NUMBER&&<> · City registration {site.CITY_LICENSE_NUMBER}</>}{site.LICENSED&&site.LICENSE_NUMBER&&<> · Licensed · License #{site.LICENSE_NUMBER}</>}{site.INSURED&&<> · Insured</>}</span><div><Link href="/privacy">Privacy</Link><Link href="/sms">SMS terms</Link></div></div></footer>}
export default Header;

export function CallLine(){return <p className="call-line">Or call <a href={site.PHONE_HREF}>{site.PHONE_MAIN}</a></p>}
